#!/usr/bin/env python3
"""
Kali-GPT v5.0 - Workflow Orchestrator
4-phase penetration testing: Recon → Scan → Exploit → Report
"""

import asyncio
import json
import os
import re
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import sys
v5_path = str(Path(__file__).parent.parent)
if v5_path not in sys.path:
    sys.path.insert(0, v5_path)

from exploitation.engine import ExploitationEngine, Finding, ValidatedExploit, Severity, ProofOfConcept
from agents.parallel_agents import ParallelVulnHunter, ReconResult
from analysis.source_analyzer import SourceCodeAnalyzer, SourceCodeFinding


@dataclass
class PentestConfig:
    target_url: str
    source_code_path: Optional[str] = None
    scan_type: str = "full"
    enabled_agents: List[str] = field(default_factory=list)
    max_exploitation_attempts: int = 10
    timeout_minutes: int = 120
    output_dir: str = "./reports"
    skip_recon: bool = False
    skip_exploitation: bool = False
    use_browser: bool = True
    proxy: Optional[str] = None
    rate_limit: float = 0.0
    hf_token: Optional[str] = None

    def __post_init__(self):
        if not self.enabled_agents:
            self.enabled_agents = ["sqli", "xss", "auth_bypass", "ssrf", "idor",
                                   "command_injection", "lfi", "ssti", "xxe", "open_redirect"]


@dataclass
class PentestReport:
    target: str
    start_time: datetime
    end_time: datetime
    duration_seconds: float
    recon_results: Optional[ReconResult]
    source_code_findings: List[SourceCodeFinding]
    all_findings: List[Finding]
    validated_exploits: List[ValidatedExploit]
    discarded_findings: List[Finding]
    stats: Dict[str, Any] = field(default_factory=dict)

    def to_markdown(self):
        md = f"""# Penetration Test Report

## Executive Summary

| Metric | Value |
|--------|-------|
| **Target** | {self.target} |
| **Date** | {self.start_time.strftime('%Y-%m-%d %H:%M')} |
| **Duration** | {self.duration_seconds/60:.1f} minutes |
| **Validated Vulnerabilities** | {len(self.validated_exploits)} |
| **False Positives Eliminated** | {len(self.discarded_findings)} |

### Severity Breakdown

| Severity | Count |
|----------|-------|
| Critical | {self.stats.get('critical', 0)} |
| High | {self.stats.get('high', 0)} |
| Medium | {self.stats.get('medium', 0)} |
| Low | {self.stats.get('low', 0)} |

---

## Validated Vulnerabilities

"""
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_exploits = sorted(self.validated_exploits, key=lambda x: severity_order.get(x.finding.severity.value, 5))
        for i, exploit in enumerate(sorted_exploits, 1):
            f = exploit.finding
            md += f"""
### {i}. {f.title}

| Property | Value |
|----------|-------|
| **Severity** | {f.severity.value.upper()} |
| **CVSS Score** | {exploit.cvss_score} |
| **CWE** | {exploit.cwe_id or 'N/A'} |
| **Endpoint** | `{f.endpoint}` |
| **Parameter** | `{f.parameter or 'N/A'}` |

{exploit.poc.to_markdown()}

**Remediation:** {exploit.remediation}

---
"""
        if self.source_code_findings:
            md += f"\n## Source Code Analysis Findings\n\n"
            for sf in self.source_code_findings[:20]:
                md += f"- **{sf.title}** in `{sf.file}:{sf.line}` ({sf.severity}) - {sf.recommendation}\n"

        md += f"\n\n---\n*Report generated by Kali-GPT v5.0*\n"
        return md

    def to_json(self):
        return json.dumps({
            "target": self.target, "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat(), "duration_seconds": self.duration_seconds,
            "statistics": self.stats,
            "validated_vulnerabilities": [
                {"title": e.finding.title, "type": e.finding.vuln_type, "severity": e.finding.severity.value,
                 "cvss": e.cvss_score, "cwe": e.cwe_id, "endpoint": e.finding.endpoint,
                 "parameter": e.finding.parameter, "payload": e.payload, "remediation": e.remediation}
                for e in self.validated_exploits],
            "false_positives_count": len(self.discarded_findings),
        }, indent=2)


class Reconnaissance:
    def __init__(self, llm_provider=None, proxy: Optional[str] = None, rate_limit: float = 0.0):
        self.llm = llm_provider
        self.proxy = proxy
        self.rate_limit = rate_limit

    async def scan(self, target_url):
        print(f"\n{'='*60}\nPHASE 1: RECONNAISSANCE\nTarget: {target_url}\n{'='*60}\n")
        result = ReconResult(target_url=target_url, endpoints=[], forms=[], technologies=[], headers={},
                             cookies=[], source_code_path=None, subdomains=[], ports={}, js_files=[],
                             api_endpoints=[], auth_endpoints=[], file_upload_endpoints=[])
        print("[*] Crawling web application...")
        await self._crawl_web(target_url, result)
        print("[*] Detecting technologies...")
        await self._detect_technologies(target_url, result)
        print("[*] Identifying authentication endpoints...")
        self._find_auth_endpoints(result)
        print(f"\n[+] Reconnaissance complete!")
        print(f"    Endpoints found: {len(result.endpoints)}")
        print(f"    Forms found: {len(result.forms)}")
        print(f"    Technologies: {', '.join(result.technologies[:5])}")
        return result

    async def _crawl_web(self, target_url, result):
        import aiohttp
        from urllib.parse import urljoin, urlparse, parse_qs
        visited, to_visit = set(), [target_url]
        async with aiohttp.ClientSession() as session:
            while to_visit and len(visited) < 100:
                if self.rate_limit:
                    await asyncio.sleep(self.rate_limit)
                url = to_visit.pop(0)
                if url in visited:
                    continue
                visited.add(url)
                try:
                    async with session.get(url, timeout=aiohttp.ClientTimeout(total=10), ssl=False, proxy=self.proxy) as resp:
                        html = await resp.text()
                        if not result.headers:
                            result.headers = dict(resp.headers)
                        for match in re.finditer(r'href=["\']([^"\']+)["\']', html):
                            href = match.group(1)
                            if not href.startswith(('javascript:', 'mailto:', '#')):
                                full = urljoin(target_url, href)
                                if urlparse(full).netloc == urlparse(target_url).netloc and full not in visited:
                                    to_visit.append(full)
                        for fm in re.finditer(r'<form[^>]*>(.*?)</form>', html, re.DOTALL | re.I):
                            form_html = fm.group(0)
                            action_m = re.search(r'action=["\']([^"\']*)["\']', form_html)
                            action = urljoin(url, action_m.group(1)) if action_m else url
                            method_m = re.search(r'method=["\']([^"\']*)["\']', form_html, re.I)
                            method = method_m.group(1).upper() if method_m else "GET"
                            inputs = []
                            for im in re.finditer(r'<input[^>]*>', form_html, re.I):
                                nm = re.search(r'name=["\']([^"\']*)["\']', im.group(0))
                                tm = re.search(r'type=["\']([^"\']*)["\']', im.group(0))
                                if nm:
                                    inputs.append({"name": nm.group(1), "type": tm.group(1) if tm else "text"})
                            for tam in re.finditer(r'<textarea[^>]*name=["\']([^"\']*)["\']', form_html, re.I):
                                inputs.append({"name": tam.group(1), "type": "textarea"})
                            result.forms.append({"action": action, "method": method, "inputs": inputs})
                        parsed = urlparse(url)
                        if parsed.query:
                            result.endpoints.append({"url": url, "method": "GET", "params": list(parse_qs(parsed.query).keys())})
                        for jsm in re.finditer(r'<script[^>]*src=["\']([^"\']+)["\']', html, re.I):
                            result.js_files.append(urljoin(target_url, jsm.group(1)))
                except Exception:
                    continue

    async def _detect_technologies(self, target_url, result):
        import aiohttp
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(target_url, timeout=aiohttp.ClientTimeout(total=10), ssl=False, proxy=self.proxy) as resp:
                    headers = dict(resp.headers)
                    html = await resp.text()
                    for h, tech in {"X-Powered-By": None, "Server": None, "X-AspNet-Version": "ASP.NET"}.items():
                        if h in headers:
                            result.technologies.append(tech or headers[h])
                    sigs = {"wp-content": "WordPress", "drupal": "Drupal", "laravel": "Laravel", "django": "Django",
                            "flask": "Flask", "express": "Express.js", "react": "React", "angular": "Angular",
                            "vue": "Vue.js", "next": "Next.js", "spring": "Spring"}
                    html_l = html.lower()
                    for sig, tech in sigs.items():
                        if sig in html_l:
                            result.technologies.append(tech)
                    result.technologies = list(set(result.technologies))
        except Exception as e:
            print(f"[!] Technology detection failed: {e}")

    def _find_auth_endpoints(self, result):
        kw = ["login", "signin", "sign-in", "auth", "session", "logout", "register", "signup", "password"]
        for ep in result.endpoints:
            if any(k in ep["url"].lower() for k in kw):
                result.auth_endpoints.append(ep["url"])
        for form in result.forms:
            if any(k in form["action"].lower() for k in kw):
                result.auth_endpoints.append(form["action"])
            if any(inp.get("type") == "password" for inp in form.get("inputs", [])):
                result.auth_endpoints.append(form["action"])
        result.auth_endpoints = list(set(result.auth_endpoints))


class PentestOrchestrator:
    def __init__(self, config, llm_provider=None):
        self.config = config
        self.llm = llm_provider
        self.reconnaissance = Reconnaissance(llm_provider, proxy=config.proxy, rate_limit=config.rate_limit)
        self.source_analyzer = SourceCodeAnalyzer(llm_provider)
        self.vuln_hunter = ParallelVulnHunter(llm_provider, config.enabled_agents, proxy=config.proxy, rate_limit=config.rate_limit)
        self.exploitation_engine = ExploitationEngine(llm_provider, use_browser=config.use_browser, proxy=config.proxy, rate_limit=config.rate_limit)

    async def run(self):
        print(f"\n{'#'*60}\n#  KALI-GPT v5.0 - PENETRATION TEST\n#  Target: {self.config.target_url}\n#  Mode: {self.config.scan_type}\n{'#'*60}\n")
        start_time = datetime.now()

        # Phase 1
        if not self.config.skip_recon:
            recon_result = await self.reconnaissance.scan(self.config.target_url)
        else:
            recon_result = ReconResult(target_url=self.config.target_url, endpoints=[{"url": self.config.target_url, "method": "GET", "params": []}],
                                       forms=[], technologies=[], headers={}, cookies=[], source_code_path=self.config.source_code_path,
                                       subdomains=[], ports={}, js_files=[], api_endpoints=[], auth_endpoints=[], file_upload_endpoints=[])

        # Source code analysis
        source_findings = []
        if self.config.source_code_path:
            result = self.source_analyzer.analyze_repository(self.config.source_code_path)
            source_findings = result.get("findings", [])

        # Phase 2
        print(f"\n{'='*60}\nPHASE 2: VULNERABILITY ANALYSIS\n{'='*60}\n")
        all_findings = await self.vuln_hunter.hunt(self.config.target_url, recon_result)

        # Phase 3
        validated_exploits, discarded = [], []
        if not self.config.skip_exploitation and all_findings:
            print(f"\n{'='*60}\nPHASE 3: EXPLOITATION (PROOF-BY-EXPLOIT)\n{'='*60}\n")
            validated_exploits = await self.exploitation_engine.validate_all(
                all_findings,
                max_attempts=self.config.max_exploitation_attempts,
            )
            discarded = self.exploitation_engine.discarded_findings

        # Phase 4
        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()
        stats = {"critical": sum(1 for e in validated_exploits if e.finding.severity == Severity.CRITICAL),
                 "high": sum(1 for e in validated_exploits if e.finding.severity == Severity.HIGH),
                 "medium": sum(1 for e in validated_exploits if e.finding.severity == Severity.MEDIUM),
                 "low": sum(1 for e in validated_exploits if e.finding.severity == Severity.LOW),
                 "total_findings_tested": len(all_findings), "validated": len(validated_exploits),
                 "false_positives": len(discarded), "agents_used": self.config.enabled_agents,
                 "source_code_findings": len(source_findings)}

        report = PentestReport(target=self.config.target_url, start_time=start_time, end_time=end_time,
                               duration_seconds=duration, recon_results=recon_result,
                               source_code_findings=source_findings, all_findings=all_findings,
                               validated_exploits=validated_exploits, discarded_findings=discarded, stats=stats)

        output_dir = Path(self.config.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        ts = start_time.strftime("%Y%m%d_%H%M%S")
        md_path = output_dir / f"pentest_report_{ts}.md"
        with open(md_path, "w") as f:
            f.write(report.to_markdown())
        print(f"\n[+] Report saved: {md_path}")
        json_path = output_dir / f"pentest_report_{ts}.json"
        with open(json_path, "w") as f:
            f.write(report.to_json())
        print(f"[+] JSON data saved: {json_path}")

        print(f"\n{'#'*60}\n#  PENETRATION TEST COMPLETE\n{'#'*60}")
        print(f"\nTarget: {report.target}\nDuration: {report.duration_seconds/60:.1f} minutes\n")
        print(f"RESULTS:\n  🔴 Critical: {stats.get('critical',0)}\n  🟠 High: {stats.get('high',0)}")
        print(f"  🟡 Medium: {stats.get('medium',0)}\n  🟢 Low: {stats.get('low',0)}\n")
        print(f"VALIDATION:\n  ✓ Validated exploits: {len(validated_exploits)}")
        print(f"  ✗ False positives eliminated: {len(discarded)}\n")
        print(f"Source code findings: {len(source_findings)}\n")

        await self.exploitation_engine.cleanup()
        return report


async def main():
    import argparse
    parser = argparse.ArgumentParser(description="Kali-GPT v5.0")
    parser.add_argument("target", help="Target URL")
    parser.add_argument("--source", "-s", help="Source code path")
    parser.add_argument("--output", "-o", default="./reports")
    parser.add_argument("--quick", action="store_true")
    parser.add_argument("--skip-exploit", action="store_true")
    args = parser.parse_args()
    config = PentestConfig(target_url=args.target, source_code_path=args.source, output_dir=args.output,
                           scan_type="quick" if args.quick else "full", skip_exploitation=args.skip_exploit)
    orchestrator = PentestOrchestrator(config)
    return await orchestrator.run()


if __name__ == "__main__":
    asyncio.run(main())

__all__ = ["PentestOrchestrator", "PentestConfig", "PentestReport", "Reconnaissance"]
